FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/dist/unichat /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
